project_id = "tggdjeoxvpzbigbikpfy"

[functions.sendcloud-webhook]
verify_jwt = false

[functions.sendcloud-orders-batch]
verify_jwt = false

[functions.n8n-gateway]
verify_jwt = false

[functions.apply-automatic-rules]
verify_jwt = true
